# Task Name: (Required) 
task_name: 'Free SONO Task'
# Task Author: (Required) 
author: 'Reverie Field'

markdownDescriptionPath: "./TaskDescription.md"

# Task Description
description: ''
# Repository URL: (Required)
repositoryUrl: 'https://github.com/CatchTheRecord/free-sono-task' 
# Image URL: (Required) Will be displayed in desktop node
imageUrl: 'https://catchtherecord.com/files/1344110/bf28e5c7-900d-42b3-a23b-3c6304457fe4.png'
# Info URL: (Required) Will be displayed in desktop node
infoUrl: 'https://www.koii.network/ocean/SONO'

# Task executable network: (Required | DEVELOPMENT, ARWEAVE, or IPFS) : IPFS is the default and common value
task_executable_network: 'IPFS'

# Task audit program: (Required) IPFS: Path to your executable | DEVELOPMENT: Leave it as 'main'
task_audit_program: 'dist/main.js'

# Round time: (Required) Duration of task, measured in slots (with each slot approximately equal to 408ms).
round_time: 8800

# Audit window: (Required) The audit window should be greater than 1/3 of the round time.
audit_window: 4000

# Submission window: (Required) The submission window should be greater than 1/3 of the round time.
submission_window: 4000

# Minimum stake amount: (Required) The minimum amount of KOII that a user must stake in order to participate in the task.
minimum_stake_amount: 0.1

# Task Bounty Type: (Required | KOII or KPL) 
task_type: 'KPL'

# Token Mint Address: (ONLY task_type == KPL) SOMA.
token_type: "BY5Vjkd34oK9QeahjPdTPkQFGBawFycSrkDSqE8JXqc5"

# Total bounty amount:  (Required) The total bounty amount that will be distributed to the task. (Not accepted in case of update task).
total_bounty_amount: 500000

# Bounty amount per round: (Required) Every round's maximum distribution, you can decide the logics in your task. 
bounty_amount_per_round: 3000

# Allowed failed distributions: (Required) Number of times re-submission is allowed for the distribution list in case of an audit, it is also the rounds of submission it will keep. 
allowed_failed_distributions: 3

# Space: (Required) Expected Task Data Size in MBs for the account size. 
# Minimum: 1 for production, 0.1 for testing; Calculation Details: https://www.koii.network/docs/develop/command-line-tool/create-task-cli/create-task#space
space: 2

# Requirement Tags: (Optional): To add more global variables and task variables, please refer to the type, value, description format shown below.
requirementsTags:
  - type: CPU
    value: '4-core'
  - type: RAM
    value: '4 GB'
  - type: STORAGE
    value: '2 GB'
    
# Tags: You can select the tags here via https://www.koii.network/docs/develop/command-line-tool/create-task-cli/create-task#tags
tags: ["DATA", "audio", "SONO", "web3gaming"]
# Environment: (Required | TEST or PRODUCTION) Production mode will expose your task to all the task runners. 
environment: "PRODUCTION"

#################################### BELOW IS FOR UPDATE TASK ONLY ####################################
# Old Task ID: (ONLY for task update) 
task_id: ''

# Migration Description: (ONLY for task update)
migrationDescription: ''
